### ISSUE TITLE
您好，请问怎么测试其他数据集啊？如S3DIS

### ISSUE THREAD

**Issue by SC-shendazt** [antao97/SegGroup#4]
您好，请问怎么测试其他数据集啊？如S3DIS

**Comment by antao97** [comment]
对于S3DIS你需要获取过分割块，在过分割块的基础上做

**Comment by SC-shendazt** [comment]
> 对于S3DIS你需要获取过分割块，在过分割块的基础上做

是用SPG算法来获取么，我看你写的是SCANNET是数据集网站上有这个过分割的结果

**Comment by antao97** [comment]
可以用SPG

**Comment by SC-shendazt** [comment]
> 可以用SPG
您好，感谢你的回复，能加个微信吗，想跟您交流交流，我也是最近在做弱监督点云语义分割，我的微信是shendaln
